# Podfile

platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  generated_xcconfig = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcconfig)
    abort "Generated.xcconfig must exist. Run 'flutter pub get' first."
  end
  IO.read(generated_xcconfig).scan(/FLUTTER_FRAMEWORK_DIR=(.*)/) do |match|
    ENV['FLUTTER_FRAMEWORK_DIR'] = match[0]
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__)

flutter_installation
install_all_flutter_pods

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # Excluir arquitecturas no soportadas
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7'
    end
  end
end
