platform :ios, '12.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

workspace 'Runner.xcworkspace'  # Asegúrate de que esta línea esté aquí

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
  
  # Firebase pods
  pod 'Firebase/Core', '6.34.0'
  pod 'Firebase/Auth', '6.34.0'
  pod 'Firebase/Firestore', '6.34.0'
  pod 'Firebase/Storage', '6.34.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'  # Cambié a 12.0 como corresponda
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
