name: Flutter iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 1: Verificar y configurar Flutter
    - name: Check Flutter installation
      run: |
        flutter --version  # Verificar la versión de Flutter
        flutter channel stable  # Asegurarse de que estamos en el canal stable
        flutter upgrade  # Actualizar Flutter si es necesario

    # Paso 2: Configurar Xcode
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Instalar CocoaPods
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    # Paso 4: Obtener dependencias
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --repo-update
        
    # Paso 5: Construir IPA
    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign --verbose
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r Runner.ipa Payload
        
    # Paso 6: Subir artefacto
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/iphoneos/Runner.ipa
        retention-days: 1
