name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter manualmente (solución definitiva)
    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        flutter precache --ios
        flutter --version
        
    # Paso 2: Configurar entorno iOS
    - name: Set up iOS
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Obtener dependencias
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --repo-update
        
    # Paso 4: Build iOS
    - name: Build IPA
      run: flutter build ios --release --no-codesign
      
    # Paso 5: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
