name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.2'
        
    - run: flutter pub get
    
    - run: flutter build ios --release --no-codesign
    
    - uses: actions/upload-artifact@v2
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
