name: Flutter iOS Build with Firebase

on: [push]

env:
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.4'
        channel: 'stable'
        
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --repo-update
        
    - name: Build and Distribute
      run: |
        flutter build ios --release --no-codesign
        cd ios
        fastlane run firebase_app_distribution \
          app:$FIREBASE_APP_ID \
          firebase_cli_token:$FIREBASE_TOKEN \
          groups: testers
