name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Configurar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        sudo gem install cocoapods -v 1.12.1
        
    # Paso 3: Regenerar proyecto iOS
    - name: Recreate iOS project
      run: |
        ~/flutter/bin/flutter clean
        rm -rf ios .ios
        ~/flutter/bin/flutter create --platforms ios --project-name wink .
        
    # Paso 4: Configurar Podfile con solución específica
    - name: Configure Podfile
      run: |
        cd ios
        # Crear Podfile optimizado
        cat <<EOF > Podfile
        platform :ios, '12.0'
        use_frameworks! :linkage => :static
        
        target 'Runner' do
          pod 'FirebaseFirestore', '10.15.0'
          pod 'FirebaseAuth', '10.15.0'
          pod 'FirebaseCore', '10.15.0'
          pod 'FirebaseStorage', '10.15.0'
          pod 'Flutter', :modular_headers => false
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
              end
            end
            installer.pods_project.build_configurations.each do |config|
              config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            end
          end
        end
        EOF
        
        # Limpiar cache de CocoaPods
        pod cache clean --all
        pod repo update
        pod install --verbose
        
    # Paso 5: Corregir proyecto Xcode
    - name: Fix Xcode project
      run: |
        cd ios
        /usr/libexec/PlistBuddy -c "Set :ALWAYS_SEARCH_USER_PATHS NO" Runner.xcodeproj/project.pbxproj
        /usr/libexec/PlistBuddy -c "Set :CLANG_ENABLE_MODULES YES" Runner.xcodeproj/project.pbxproj
        /usr/libexec/PlistBuddy -c "Delete :EXCLUDED_ARCHS" Runner.xcodeproj/project.pbxproj
        
    # Paso 6: Construir IPA
    - name: Build IPA
      run: |
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean build
        
    # Paso 7: Empaquetar IPA
    - name: Package IPA
      run: |
        mkdir -p build/ios/ipa/Payload
        cp -r ios/build/Release-iphoneos/Runner.app build/ios/ipa/Payload
        cd build/ios/ipa
        zip -r Runner.ipa Payload
        
    # Paso 8: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
