name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Configurar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        flutter --version
        flutter precache --ios
        
    # Paso 2: Configurar iOS
    - name: Set up iOS
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Actualizar Podfile
    - name: Update Podfile
      run: |
        echo "=== Actualizando Podfile ==="
        cd ios
        # Asegurar platform iOS 12.0 o superior
        sed -i '' "s/platform :ios.*/platform :ios, '12.0'/" Podfile
        # Agregar configuración de Firebase
        echo "
        post_install do |installer|
          installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
          end
        end
        " >> Podfile
        cat Podfile
        
    # Paso 4: Obtener dependencias
    - name: Get dependencies
      run: |
        echo "=== Obteniendo dependencias ==="
        flutter pub get
        cd ios
        pod repo update
        pod install --repo-update
        
    # Paso 5: Build IPA
    - name: Build IPA
      run: |
        echo "=== Construyendo IPA ==="
        flutter build ios --release --no-codesign
        
    # Paso 6: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
