name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Configurar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        flutter precache --ios
        flutter --version
        
    # Paso 2: Configurar Xcode
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Generar archivos iOS
    - name: Generate iOS files
      run: flutter pub get && flutter gen-l10n && flutter create --platforms ios .
        
    # Paso 4: Instalar dependencias iOS
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        
    # Paso 5: Build IPA
    - name: Build IPA
      run: flutter build ios --release --no-codesign
      
    # Paso 6: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
