name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Configuración inicial
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        flutter --version
        
    # Paso 2: Regenerar estructura iOS
    - name: Generate iOS files
      run: |
        flutter clean
        rm -rf ios .ios
        flutter create --platforms ios --project-name wink .
        
    # Paso 3: Configurar entorno iOS
    - name: Set up iOS environment
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 4: Obtener dependencias
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --repo-update
        
    # Paso 5: Build IPA
    - name: Build IPA
      run: flutter build ios --release --no-codesign
      
    # Paso 6: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
