name: Build and Distribute iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.22.3'
        
    - run: flutter pub get
    
    - run: flutter build ios --release
    
    - run: |
        cd ios
        pod install
        
        # Configura Firebase (necesitarás crear estos secrets en GitHub)
        echo ${{ secrets.FIREBASE_CONFIG }} > Runner/firebase_config.json
        
        # Instala fastlane si no está presente
        sudo gem install fastlane -NV
        
        # Distribuye a Firebase
        fastlane run firebase_app_distribution \
          app:${{ secrets.FIREBASE_APP_ID }} \
          firebase_cli_token:${{ secrets.FIREBASE_TOKEN }} \
          groups: "testers"
