name: Flutter iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.4'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-3.22.4'
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --repo-update
        
    - name: Build iOS (Release)
      run: |
        flutter build ios --release --no-codesign --verbose
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r Runner.ipa Payload
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/iphoneos/Runner.ipa
        retention-days: 1
