name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Configurar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Regenerar proyecto iOS
    - name: Recreate iOS project
      run: |
        ~/flutter/bin/flutter clean
        rm -rf ios .ios
        ~/flutter/bin/flutter create --platforms ios --project-name wink .
        
    # Paso 4: Configurar Podfile correctamente
    - name: Configure Podfile
      run: |
        cd ios
        cat <<EOF > Podfile
        platform :ios, '12.0'
        target 'Runner' do
          use_frameworks!
          use_modular_headers!
          
          # Firebase pods
          pod 'FirebaseCore'
          pod 'FirebaseFirestore'
          pod 'FirebaseAuth'
          pod 'FirebaseStorage'
          
          # Flutter pod
          pod 'Flutter', :modular_headers => false
          
          # Configuración post-install
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
              end
            end
            installer.pods_project.build_configurations.each do |config|
              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            end
          end
        end
        EOF
        
        cat Podfile
        
    # Paso 5: Instalar dependencias
    - name: Install dependencies
      run: |
        ~/flutter/bin/flutter pub get
        cd ios
        pod repo update
        pod install --repo-update --verbose
        
    # Paso 6: Configurar proyecto Xcode
    - name: Configure Xcode project
      run: |
        cd ios
        /usr/bin/xcodebuild -project Runner.xcodeproj -scheme Runner -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        
    # Paso 7: Construir IPA
    - name: Build IPA
      run: |
        ~/flutter/bin/flutter build ios --release --no-codesign --verbose
        
    # Paso 8: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
