name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.4'  # Usar una versión estable que soporte Dart 3.5.3+

    - name: Check Flutter and Dart version
      run: |
        flutter --version
        dart --version

    - name: Install Dependencies
      run: |
        flutter pub get
        flutter doctor

    - name: Build iOS
      run: flutter build ios --release

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-ios
        path: build/ios/iphoneos/Runner.ipa
