name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode y CocoaPods
    - name: Set up Xcode and CocoaPods
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    # Paso 3: Crear proyecto iOS y generar el .xcworkspace
    - name: Generate iOS Project and .xcworkspace
      run: |
        cd ios
        flutter create .
        flutter pub get
        pod install
        
    # Paso 4: Configurar Podfile
    - name: Clean and Configure Podfile
      run: |
        cd ios
        echo "platform :ios, '12.0'" > Podfile
        echo "flutter_application_path = '../'" >> Podfile
        echo "load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')" >> Podfile
        echo "target 'Runner' do" >> Podfile
        echo "  use_frameworks!" >> Podfile
        echo "  use_modular_headers!" >> Podfile
        echo "" >> Podfile
        echo "  install_all_flutter_pods(flutter_application_path)" >> Podfile
        echo "" >> Podfile
        echo "  # Firebase pods" >> Podfile
        echo "  pod 'Firebase/Core', '6.34.0'" >> Podfile
        echo "  pod 'Firebase/Auth', '6.34.0'" >> Podfile
        echo "  pod 'Firebase/Firestore', '6.34.0'" >> Podfile
        echo "  pod 'Firebase/Storage', '6.34.0'" >> Podfile
        echo "end" >> Podfile
        echo "" >> Podfile
        echo "post_install do |installer|" >> Podfile
        echo "  installer.pods_project.targets.each do |target|" >> Podfile
        echo "    target.build_configurations.each do |config|" >> Podfile
        echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'" >> Podfile
        echo "      config.build_settings['ENABLE_BITCODE'] = 'NO'" >> Podfile
        echo "      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'" >> Podfile
        echo "    end" >> Podfile
        echo "  end" >> Podfile
        echo "end" >> Podfile

        pod install --verbose

    # Paso 5: Build IPA
    - name: Build IPA
      run: |
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean build

    # Paso 6: Empaquetar IPA
    - name: Package IPA
      run: |
        mkdir -p build/ios/ipa/Payload
        cp -r ios/build/Release-iphoneos/Runner.app build/ios/ipa/Payload
        cd build/ios/ipa
        zip -r Runner.ipa Payload
        
    # Paso 7: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
        retention-days: 1
