name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter usando método garantizado
    - name: Install Flutter
      run: |
        echo "=== Descargando Flutter ==="
        # Descargar usando la URL oficial de GitHub
        FLUTTER_VERSION="3.22.4"
        curl -L https://github.com/flutter/flutter/releases/download/${FLUTTER_VERSION}-stable/flutter_macos_${FLUTTER_VERSION}-stable.zip -o flutter.zip --retry 3 --retry-delay 5
        echo "=== Verificando integridad del archivo ==="
        unzip -t flutter.zip
        echo "=== Descomprimiendo ==="
        unzip flutter.zip -d ~
        echo "=== Configurando PATH ==="
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        export PATH="$HOME/flutter/bin:$PATH"
        echo "=== Verificando instalación ==="
        ls -la ~/flutter/bin
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Resto del workflow permanece igual...
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    - name: Generate iOS files
      run: |
        flutter clean
        rm -rf ios .ios
        flutter create --platforms ios --project-name wink .
        
    - name: Configure iOS environment
      run: |
        cd ios
        echo "platform :ios, '12.0'" > Podfile
        echo "target 'Runner' do" >> Podfile
        echo "  use_frameworks!" >> Podfile
        echo "  pod 'Firebase/CoreOnly', '10.15.0'" >> Podfile
        echo "end" >> Podfile
        
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios
        pod repo update
        pod install --repo-update
        
    - name: Build IPA
      run: flutter build ios --release --no-codesign
        
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
