name: Flutter iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 1: Instalar Flutter (si no está instalado)
    - name: Install Flutter
      run: |
        echo "=== Instalando Flutter ==="
        # Descargar Flutter si no está instalado
        git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
        # Asegurarnos de que Flutter esté en el PATH correctamente para todos los pasos
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        flutter --version  # Verificar que Flutter esté correctamente instalado

    # Paso 2: Configurar Xcode
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Instalar CocoaPods
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    # Paso 4: Obtener dependencias
    - name: Get dependencies
      run: |
        flutter pub get
        cd ios
        pod install --r
