name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter con configuración explícita del PATH
    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        FLUTTER_PATH="$GITHUB_WORKSPACE/flutter/bin"
        echo "FLUTTER_PATH=$FLUTTER_PATH" >> $GITHUB_ENV
        echo "$FLUTTER_PATH" >> $GITHUB_PATH
        export PATH="$FLUTTER_PATH:$PATH"
        $FLUTTER_PATH/flutter precache --ios
        $FLUTTER_PATH/flutter --version
        
    # Paso 2: Verificar instalación
    - name: Verify Flutter
      run: |
        echo "PATH: $PATH"
        which flutter
        flutter doctor -v
        
    # Paso 3: Configurar Xcode
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 4: Generar archivos iOS
    - name: Generate iOS files
      run: |
        flutter pub get
        flutter create --platforms ios .
        
    # Paso 5: Instalar dependencias iOS
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        
    # Paso 6: Build IPA
    - name: Build IPA
      run: flutter build ios --release --no-codesign
      
    # Paso 7: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
