name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Paso 1: Configurar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode y CocoaPods
    - name: Set up Xcode and CocoaPods
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        sudo gem install cocoapods -v 1.12.1
        
    # Paso 3: Regenerar proyecto iOS
    - name: Recreate iOS project
      run: |
        ~/flutter/bin/flutter clean
        rm -rf ios .ios
        ~/flutter/bin/flutter create --platforms ios --project-name wink .
        
    # Paso 4: Limpiar y configurar Pods
    - name: Clean and Configure Podfile
      run: |
        cd ios
        # Limpiar caché de pods y actualizar repositorios
        pod cache clean --all
        pod repo update
        pod install --repo-update --verbose

    # Paso 5: Verificar existencia del directorio de salida
    - name: Verify Output Directory Existence
      run: |
        ls ios/build/
        ls ios/build/Release-iphoneos/
        ls ios/build/Release-iphoneos/Runner.app
        
    # Paso 6: Construir IPA
    - name: Build IPA
      run: |
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean build
        
    # Paso 7: Empaquetar IPA
    - name: Package IPA
      run: |
        mkdir -p build/ios/ipa/Payload
        cp -r ios/build/Release-iphoneos/Runner.app build/ios/ipa/Payload
        cd build/ios/ipa
        zip -r Runner.ipa Payload
        
    # Paso 8: Subir artefacto
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
        retention-days: 1
