name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode y CocoaPods
    - name: Set up Xcode and CocoaPods
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        sudo gem install cocoapods -v 1.12.1
        pod setup
        
    # Paso 3: Crear proyecto iOS y generar el .xcworkspace
    - name: Generate iOS Project and .xcworkspace
      run: |
        cd ios
        flutter create .
        flutter pub get
        pod install
        
    # Paso 4: Configurar Podfile (agregamos dependencias y configuramos)
    - name: Clean and Configure Podfile
      run: |
        cd ios
        cat <<EOF > Podfile
platform :ios, '12.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

workspace 'Runner.xcworkspace'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
  
  # Firebase pods
  pod 'Firebase/Core', '6.34.0'
  pod 'Firebase/Auth', '6.34.0'
  pod 'Firebase/Firestore', '6.34.0'
  pod 'Firebase/Storage', '6.34.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
EOF

        pod install --verbose

    # Paso 5: Build IPA
    - name: Build IPA
      run: |
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean build

    # Paso 6: Empaquetar IPA
    - name: Package IPA
      run: |
        mkdir -p build/ios/ipa/Payload
        cp -r ios/build/Release-iphoneos/Runner.app build/ios/ipa/Payload
        cd build/ios/ipa
        zip -r Runner.ipa Payload
        
    # Paso 7: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
        retention-days: 1
