name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso crucial: Instala Flutter con la versión específica que necesitas
    - name: Set up Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
        
    - run: flutter --version  # Verifica la versión instalada
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
