name: Flutter iOS Build

on:
  push:
    branches:
      - main  # Cambia a la rama que uses para producción
  pull_request:
    branches:
      - main  # Para que se ejecute en pull requests también

jobs:
  build:
    runs-on: macos-latest  # Usar runner de macOS para compilar para iOS

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout del código

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x.x'  # Especifica la versión de Flutter que usas

    - name: Install Dependencies
      run: |
        flutter pub get
        flutter doctor

    - name: Build iOS
      run: flutter build ios --release  # Compila para iOS en modo release

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3  # Usar la versión más reciente
      with:
        name: app-ios
        path: build/ios/iphoneos/Runner.ipa  # Especifica el archivo IPA que se genera
