name: Build iOS IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Paso 1: Instalar Flutter usando método alternativo
    - name: Install Flutter (Alternative Method)
      run: |
        echo "=== Descargando Flutter ==="
        FLUTTER_VERSION="3.22.4"
        curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_${FLUTTER_VERSION}-stable.zip -o flutter.zip
        unzip flutter.zip -d ~
        echo "=== Configurando PATH ==="
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        export PATH="$HOME/flutter/bin:$PATH"
        echo "=== Verificando instalación ==="
        ~/flutter/bin/flutter --version
        ~/flutter/bin/flutter precache --ios
        
    # Paso 2: Configurar Xcode
    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
        
    # Paso 3: Regenerar estructura iOS
    - name: Generate iOS files
      run: |
        flutter clean
        rm -rf ios .ios
        flutter create --platforms ios --project-name wink .
        
    # Paso 4: Configurar Podfile
    - name: Configure iOS environment
      run: |
        cd ios
        echo "platform :ios, '12.0'" > Podfile
        echo "target 'Runner' do" >> Podfile
        echo "  use_frameworks!" >> Podfile
        echo "  pod 'Firebase/CoreOnly', '10.15.0'" >> Podfile
        echo "  pod 'Firebase/Firestore', '10.15.0'" >> Podfile
        # Agrega aquí otros pods de Firebase que necesites
        echo "end" >> Podfile
        cat Podfile
        
    # Paso 5: Instalar dependencias
    - name: Install dependencies
      run: |
        flutter pub get
        cd ios
        pod repo update
        pod install --repo-update
        
    # Paso 6: Build IPA
    - name: Build IPA
      run: flutter build ios --release --no-codesign
        
    # Paso 7: Subir artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: app-ipa
        path: build/ios/ipa/Runner.ipa
